FROM jenkins/jenkins:lts
USER root

# Instala o cliente do Docker dentro do container do Jenkins
RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://get.docker.com | sh

USER jenkins
# INSTALAÇÃO AUTOMÁTICA DE PLUGINS: Baixa o Pipeline (workflow-aggregator) e o Git
RUN jenkins-plugin-cli --plugins workflow-aggregator git